 version: 2
 jobs:
   build:
     docker:
       - image: circleci/python:3
     steps:
       - checkout
       - run:
           name: install conda and regolith and run validation
           command: |
             wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
             chmod +x miniconda.sh
             bash miniconda.sh -b -p ~/miniconda
             source ~/miniconda/etc/profile.d/conda.sh
             conda activate base
             conda update conda
             conda config --set always_yes yes --set quiet true
             conda create -n validation python=3
             conda activate validation
             conda config --add channels diffpy
             conda config --add channels conda-forge
             conda install --file https://raw.githubusercontent.com/bozer/pydatarecognition/master/requirements/run.txt
             conda install --file https://raw.githubusercontent.com/bozer/pydatarecognition/master/requirements/run.txt
             pip install git+git://github.com/bozer/pydatarecognition@master
             cd ~/project/
             pytest tests
